version: "3.3"

services:
  kafka-consumer:
    build: kafka-consumer
    depends_on:
      - kafka
  kafka-producer:
    build: kafka-producer
    ports:
      - "8080:8080"
    depends_on:
      - kafka
  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "produced-messages:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
